### ISSUE TITLE
[Crash] Something Ticking

### ISSUE THREAD

**Issue by Niconoko** [klinbee/One-Island#1]
[crash-2024-10-19_12.52.31-client.txt](https://github.com/user-attachments/files/17443216/crash-2024-10-19_12.52.31-client.txt)
[latest.log](https://github.com/user-attachments/files/17443218/latest.log)
Crash on loading in the game (´・ω・｀)

**Comment by klinbee** [comment]
This is almost certainly something else, you are using a mod pack. This is a single data pack, which has zero code modification. Even the mod dependency doesn't show up in the stack trace. Seems most likely to be from Xaero's.

**Comment by Niconoko** [comment]
Me clueless when come to this, will have a look again. (´ - ω -｀)

**Comment by Niconoko** [comment]
Just an update, seem like it was some mods me updated before testing out this mod, it's working just fine now. (´>ω <｀)
